readingDataPointsFilters:
   - IdentityDataPointsFilter

referenceDataPointsFilters:
   - SamplingSurfaceNormalDataPointsFilter:
      knn: 10
      ratio: 1

matcher:
  KDTreeMatcher:
    knn: 1
    epsilon: 0 

outlierFilters:
   - NullOutlierFilter

errorMinimizer:
   PointToPlaneErrorMinimizer

transformationCheckers:
   - CounterTransformationChecker:
      maxIterationCount: 100

inspector:
   VTKFileInspector

logger:
   FileLogger


